# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainAppWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainAppWindow(object):
    def setupUi(self, MainAppWindow):
        MainAppWindow.setObjectName("MainAppWindow")
        MainAppWindow.resize(852, 581)
        MainAppWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainAppWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clLoginLbl = QtWidgets.QLabel(self.centralwidget)
        self.clLoginLbl.setGeometry(QtCore.QRect(410, 20, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clLoginLbl.setFont(font)
        self.clLoginLbl.setObjectName("clLoginLbl")
        self.clUsernameLbl = QtWidgets.QLabel(self.centralwidget)
        self.clUsernameLbl.setGeometry(QtCore.QRect(410, 60, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clUsernameLbl.setFont(font)
        self.clUsernameLbl.setObjectName("clUsernameLbl")
        self.clUsernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.clUsernameLineEdit.setGeometry(QtCore.QRect(560, 60, 271, 20))
        self.clUsernameLineEdit.setObjectName("clUsernameLineEdit")
        self.clPasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.clPasswordLineEdit.setGeometry(QtCore.QRect(560, 90, 270, 20))
        self.clPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.clPasswordLineEdit.setObjectName("clPasswordLineEdit")
        self.clPasswordLbl = QtWidgets.QLabel(self.centralwidget)
        self.clPasswordLbl.setGeometry(QtCore.QRect(410, 90, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPasswordLbl.setFont(font)
        self.clPasswordLbl.setObjectName("clPasswordLbl")
        self.clStartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clStartBtn.setGeometry(QtCore.QRect(620, 480, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clStartBtn.setFont(font)
        self.clStartBtn.setObjectName("clStartBtn")
        self.clProfileListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.clProfileListWidget.setGeometry(QtCore.QRect(20, 60, 311, 471))
        self.clProfileListWidget.setObjectName("clProfileListWidget")
        self.clProfileListLbl = QtWidgets.QLabel(self.centralwidget)
        self.clProfileListLbl.setGeometry(QtCore.QRect(20, 20, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clProfileListLbl.setFont(font)
        self.clProfileListLbl.setObjectName("clProfileListLbl")
        MainAppWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainAppWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainAppWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainAppWindow)
        self.statusbar.setObjectName("statusbar")
        MainAppWindow.setStatusBar(self.statusbar)
        self.actionNewProfile = QtWidgets.QAction(MainAppWindow)
        self.actionNewProfile.setObjectName("actionNewProfile")
        self.actionAbout = QtWidgets.QAction(MainAppWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainAppWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainAppWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionNewProfile)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainAppWindow)
        QtCore.QMetaObject.connectSlotsByName(MainAppWindow)

    def retranslateUi(self, MainAppWindow):
        _translate = QtCore.QCoreApplication.translate
        MainAppWindow.setWindowTitle(_translate("MainAppWindow", "RoboBot"))
        self.clLoginLbl.setText(_translate("MainAppWindow", "Craiglist Login Detail"))
        self.clUsernameLbl.setText(_translate("MainAppWindow", "Username:"))
        self.clUsernameLineEdit.setText(_translate("MainAppWindow", "nikkizurcher3113@yahoo.com"))
        self.clPasswordLineEdit.setText(_translate("MainAppWindow", "KLMNijlm37"))
        self.clPasswordLbl.setText(_translate("MainAppWindow", "Password:"))
        self.clStartBtn.setText(_translate("MainAppWindow", "Start"))
        self.clProfileListLbl.setText(_translate("MainAppWindow", "Profile List"))
        self.menuFile.setTitle(_translate("MainAppWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainAppWindow", "&Help"))
        self.actionNewProfile.setText(_translate("MainAppWindow", "&New Post Profile"))
        self.actionAbout.setText(_translate("MainAppWindow", "&About"))
        self.actionExit.setText(_translate("MainAppWindow", "E&xit"))
        self.actionSettings.setText(_translate("MainAppWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainAppWindow = QtWidgets.QMainWindow()
    ui = Ui_MainAppWindow()
    ui.setupUi(MainAppWindow)
    MainAppWindow.show()
    sys.exit(app.exec_())

