# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProfileDialog-test.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newProfileDialog(object):
    def setupUi(self, newProfileDialog):
        newProfileDialog.setObjectName("newProfileDialog")
        newProfileDialog.resize(451, 511)
        newProfileDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.clProfileNameLbl = QtWidgets.QLabel(newProfileDialog)
        self.clProfileNameLbl.setGeometry(QtCore.QRect(20, 90, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clProfileNameLbl.setFont(font)
        self.clProfileNameLbl.setObjectName("clProfileNameLbl")
        self.clProfileNameLineEdit = QtWidgets.QLineEdit(newProfileDialog)
        self.clProfileNameLineEdit.setGeometry(QtCore.QRect(160, 90, 271, 20))
        self.clProfileNameLineEdit.setText("")
        self.clProfileNameLineEdit.setObjectName("clProfileNameLineEdit")
        self.clPostDetailLbl = QtWidgets.QLabel(newProfileDialog)
        self.clPostDetailLbl.setGeometry(QtCore.QRect(20, 30, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clPostDetailLbl.setFont(font)
        self.clPostDetailLbl.setObjectName("clPostDetailLbl")
        self.clSubLocationComboBox = QtWidgets.QComboBox(newProfileDialog)
        self.clSubLocationComboBox.setGeometry(QtCore.QRect(160, 180, 270, 22))
        self.clSubLocationComboBox.setObjectName("clSubLocationComboBox")
        self.clLocationLbl = QtWidgets.QLabel(newProfileDialog)
        self.clLocationLbl.setGeometry(QtCore.QRect(20, 150, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clLocationLbl.setFont(font)
        self.clLocationLbl.setObjectName("clLocationLbl")
        self.clLocationComboBox = QtWidgets.QComboBox(newProfileDialog)
        self.clLocationComboBox.setGeometry(QtCore.QRect(160, 150, 270, 22))
        self.clLocationComboBox.setObjectName("clLocationComboBox")
        self.clSubLocationLbl = QtWidgets.QLabel(newProfileDialog)
        self.clSubLocationLbl.setGeometry(QtCore.QRect(20, 180, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clSubLocationLbl.setFont(font)
        self.clSubLocationLbl.setObjectName("clSubLocationLbl")
        self.clCreateProfileSaveBtn = QtWidgets.QPushButton(newProfileDialog)
        self.clCreateProfileSaveBtn.setGeometry(QtCore.QRect(20, 440, 171, 51))
        self.clCreateProfileSaveBtn.setObjectName("clCreateProfileSaveBtn")
        self.clPostAttrComboBox_5 = QtWidgets.QComboBox(newProfileDialog)
        self.clPostAttrComboBox_5.setGeometry(QtCore.QRect(160, 360, 270, 22))
        self.clPostAttrComboBox_5.setObjectName("clPostAttrComboBox_5")
        self.clPostAttrLbl_2 = QtWidgets.QLabel(newProfileDialog)
        self.clPostAttrLbl_2.setGeometry(QtCore.QRect(20, 270, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostAttrLbl_2.setFont(font)
        self.clPostAttrLbl_2.setObjectName("clPostAttrLbl_2")
        self.clPostAttrLbl_4 = QtWidgets.QLabel(newProfileDialog)
        self.clPostAttrLbl_4.setGeometry(QtCore.QRect(20, 330, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostAttrLbl_4.setFont(font)
        self.clPostAttrLbl_4.setObjectName("clPostAttrLbl_4")
        self.clPostAttrLbl_3 = QtWidgets.QLabel(newProfileDialog)
        self.clPostAttrLbl_3.setGeometry(QtCore.QRect(20, 300, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostAttrLbl_3.setFont(font)
        self.clPostAttrLbl_3.setObjectName("clPostAttrLbl_3")
        self.clPostAttrComboBox_1 = QtWidgets.QComboBox(newProfileDialog)
        self.clPostAttrComboBox_1.setGeometry(QtCore.QRect(160, 240, 270, 20))
        self.clPostAttrComboBox_1.setObjectName("clPostAttrComboBox_1")
        self.clPostAttrComboBox_3 = QtWidgets.QComboBox(newProfileDialog)
        self.clPostAttrComboBox_3.setGeometry(QtCore.QRect(160, 300, 270, 22))
        self.clPostAttrComboBox_3.setObjectName("clPostAttrComboBox_3")
        self.clPostTypeLbl = QtWidgets.QLabel(newProfileDialog)
        self.clPostTypeLbl.setGeometry(QtCore.QRect(20, 210, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostTypeLbl.setFont(font)
        self.clPostTypeLbl.setObjectName("clPostTypeLbl")
        self.clPostAttrLbl_5 = QtWidgets.QLabel(newProfileDialog)
        self.clPostAttrLbl_5.setGeometry(QtCore.QRect(20, 360, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostAttrLbl_5.setFont(font)
        self.clPostAttrLbl_5.setObjectName("clPostAttrLbl_5")
        self.clPostAttrComboBox_2 = QtWidgets.QComboBox(newProfileDialog)
        self.clPostAttrComboBox_2.setGeometry(QtCore.QRect(160, 270, 270, 22))
        self.clPostAttrComboBox_2.setObjectName("clPostAttrComboBox_2")
        self.clPostTypeComboBox = QtWidgets.QComboBox(newProfileDialog)
        self.clPostTypeComboBox.setGeometry(QtCore.QRect(160, 210, 270, 22))
        self.clPostTypeComboBox.setObjectName("clPostTypeComboBox")
        self.clPostAttrLbl_1 = QtWidgets.QLabel(newProfileDialog)
        self.clPostAttrLbl_1.setGeometry(QtCore.QRect(20, 240, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clPostAttrLbl_1.setFont(font)
        self.clPostAttrLbl_1.setObjectName("clPostAttrLbl_1")
        self.clPostAttrComboBox_4 = QtWidgets.QComboBox(newProfileDialog)
        self.clPostAttrComboBox_4.setGeometry(QtCore.QRect(160, 330, 270, 22))
        self.clPostAttrComboBox_4.setObjectName("clPostAttrComboBox_4")
        self.clCreateProfileCloseBtn = QtWidgets.QPushButton(newProfileDialog)
        self.clCreateProfileCloseBtn.setGeometry(QtCore.QRect(260, 440, 171, 51))
        self.clCreateProfileCloseBtn.setObjectName("clCreateProfileCloseBtn")

        self.retranslateUi(newProfileDialog)
        QtCore.QMetaObject.connectSlotsByName(newProfileDialog)

    def retranslateUi(self, newProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        newProfileDialog.setWindowTitle(_translate("newProfileDialog", "RoboBot - New Profile"))
        self.clProfileNameLbl.setText(_translate("newProfileDialog", "Profile Name:"))
        self.clPostDetailLbl.setText(_translate("newProfileDialog", "Craiglist Post Detail"))
        self.clLocationLbl.setText(_translate("newProfileDialog", "Location:"))
        self.clSubLocationLbl.setText(_translate("newProfileDialog", "Sub Location:"))
        self.clCreateProfileSaveBtn.setText(_translate("newProfileDialog", "Save"))
        self.clPostAttrLbl_2.setText(_translate("newProfileDialog", "Post Attribute #2:"))
        self.clPostAttrLbl_4.setText(_translate("newProfileDialog", "Post Attribute #4:"))
        self.clPostAttrLbl_3.setText(_translate("newProfileDialog", "Post Attribute #3:"))
        self.clPostTypeLbl.setText(_translate("newProfileDialog", "Post Type:"))
        self.clPostAttrLbl_5.setText(_translate("newProfileDialog", "Post Attribute #5:"))
        self.clPostAttrLbl_1.setText(_translate("newProfileDialog", "Post Attribute #1:"))
        self.clCreateProfileCloseBtn.setText(_translate("newProfileDialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newProfileDialog = QtWidgets.QDialog()
    ui = Ui_newProfileDialog()
    ui.setupUi(newProfileDialog)
    newProfileDialog.show()
    sys.exit(app.exec_())

